name: irc3
version: 5.0.0
description: IRC library in Dart providing a simplistic and easy to use API.
homepage: https://github.com/mysticlgbt/irc.dart/
environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  glob: any
  reflectable: any
dev_dependencies:
  lints: any
  test: any
